/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.license;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * License <code>xsi:type</code> in the
 * license namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface ILicense extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"license", "License", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("licname", "instance", "Description", 1, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the licname for this License.
	 * @param value new licname
	 */
	public void setLicname(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the licname from this License.
	 */
	public void clearLicname();

	/**
	 * Get the licname from this License.
	 * @return licname
	 */
	public edu.uci.isr.xarch.instance.IDescription getLicname();

	/**
	 * Determine if this License has the given licname
	 * @param licnameToCheck licname to compare
	 * @return <code>true</code> if the licnames are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasLicname(edu.uci.isr.xarch.instance.IDescription licnameToCheck);
	/**
	 * Determine if another License is equivalent to this one, ignoring
	 * ID's.
	 * @param LicenseToCheck License to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * License are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(ILicense LicenseToCheck);

}
