/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.licenselookup;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * Obligation <code>xsi:type</code> in the
 * licenselookup namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IObligation extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"licenselookup", "Obligation", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("id", "instance", "Identifier", null, null),
			XArchPropertyMetadata.createElement("actor", "licenselookup", "Actor", 1, 1),
			XArchPropertyMetadata.createElement("operation", "licenselookup", "Operation", 1, 1),
			XArchPropertyMetadata.createElement("action", "licenselookup", "Action", 1, 1),
			XArchPropertyMetadata.createElement("object", "licenselookup", "Object", 1, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the id attribute on this Obligation.
	 * @param id id
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setId(String id);

	/**
	 * Remove the id attribute from this Obligation.
	 */
	public void clearId();

	/**
	 * Get the id attribute from this Obligation.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return id on this Obligation
	 */
	public String getId();

	/**
	 * Determine if the id attribute on this Obligation
	 * has the given value.
	 * @param id Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasId(String id);


	/**
	 * Set the actor for this Obligation.
	 * @param value new actor
	 */
	public void setActor(IActor value);

	/**
	 * Clear the actor from this Obligation.
	 */
	public void clearActor();

	/**
	 * Get the actor from this Obligation.
	 * @return actor
	 */
	public IActor getActor();

	/**
	 * Determine if this Obligation has the given actor
	 * @param actorToCheck actor to compare
	 * @return <code>true</code> if the actors are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasActor(IActor actorToCheck);

	/**
	 * Set the operation for this Obligation.
	 * @param value new operation
	 */
	public void setOperation(IOperation value);

	/**
	 * Clear the operation from this Obligation.
	 */
	public void clearOperation();

	/**
	 * Get the operation from this Obligation.
	 * @return operation
	 */
	public IOperation getOperation();

	/**
	 * Determine if this Obligation has the given operation
	 * @param operationToCheck operation to compare
	 * @return <code>true</code> if the operations are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasOperation(IOperation operationToCheck);

	/**
	 * Set the action for this Obligation.
	 * @param value new action
	 */
	public void setAction(IAction value);

	/**
	 * Clear the action from this Obligation.
	 */
	public void clearAction();

	/**
	 * Get the action from this Obligation.
	 * @return action
	 */
	public IAction getAction();

	/**
	 * Determine if this Obligation has the given action
	 * @param actionToCheck action to compare
	 * @return <code>true</code> if the actions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasAction(IAction actionToCheck);

	/**
	 * Set the object for this Obligation.
	 * @param value new object
	 */
	public void setObject(IObject value);

	/**
	 * Clear the object from this Obligation.
	 */
	public void clearObject();

	/**
	 * Get the object from this Obligation.
	 * @return object
	 */
	public IObject getObject();

	/**
	 * Determine if this Obligation has the given object
	 * @param objectToCheck object to compare
	 * @return <code>true</code> if the objects are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasObject(IObject objectToCheck);
	/**
	 * Determine if another Obligation has the same
	 * id as this one.
	 * @param ObligationToCheck Obligation to compare with this
	 * one.
	 */
	public boolean isEqual(IObligation ObligationToCheck);
	/**
	 * Determine if another Obligation is equivalent to this one, ignoring
	 * ID's.
	 * @param ObligationToCheck Obligation to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * Obligation are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IObligation ObligationToCheck);

}
