/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.licenselookup;

import java.util.Collection;
import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * Satisfy <code>xsi:type</code> in the
 * licenselookup namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface ISatisfy extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"licenselookup", "Satisfy", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("obligationID", "instance", "XMLLink", 0, XArchPropertyMetadata.UNBOUNDED)},
		new XArchActionMetadata[]{});

	/**
	 * Add a obligationID to this Satisfy.
	 * @param newObligationID obligationID to add.
	 */
	public void addObligationID(edu.uci.isr.xarch.instance.IXMLLink newObligationID);

	/**
	 * Add a collection of obligationIDs to this Satisfy.
	 * @param obligationIDs obligationIDs to add.
	 */
	public void addObligationIDs(Collection obligationIDs);

	/**
	 * Remove all obligationIDs from this Satisfy.
	 */
	public void clearObligationIDs();

	/**
	 * Remove the given obligationID from this Satisfy.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param obligationIDToRemove obligationID to remove.
	 */
	public void removeObligationID(edu.uci.isr.xarch.instance.IXMLLink obligationIDToRemove);

	/**
	 * Remove all the given obligationIDs from this Satisfy.
	 * Matching is done by the <code>isEquivalent(...)</code> function.
	 * @param obligationIDs obligationID to remove.
	 */
	public void removeObligationIDs(Collection obligationIDs);

	/**
	 * Get all the obligationIDs from this Satisfy.
	 * @return all obligationIDs in this Satisfy.
	 */
	public Collection getAllObligationIDs();

	/**
	 * Determine if this Satisfy contains a given obligationID.
	 * @return <code>true</code> if this Satisfy contains the given
	 * obligationIDToCheck, <code>false</code> otherwise.
	 */
	public boolean hasObligationID(edu.uci.isr.xarch.instance.IXMLLink obligationIDToCheck);

	/**
	 * Determine if this Satisfy contains the given set of obligationIDs.
	 * @param obligationIDsToCheck obligationIDs to check for.
	 * @return Collection of <code>java.lang.Boolean</code>.  If the i<sup>th</sup>
	 * element in <code>obligationIDs</code> was found, then the i<sup>th</sup>
	 * element of the collection will be set to <code>true</code>, otherwise it
	 * will be set to <code>false</code>.  Matching is done with the
	 * <code>isEquivalent(...)</code> method.
	 */
	public Collection hasObligationIDs(Collection obligationIDsToCheck);

	/**
	 * Determine if this Satisfy contains each element in the 
	 * given set of obligationIDs.
	 * @param obligationIDsToCheck obligationIDs to check for.
	 * @return <code>true</code> if every element in
	 * <code>obligationIDs</code> is found in this Satisfy,
	 * <code>false</code> otherwise.
	 */
	public boolean hasAllObligationIDs(Collection obligationIDsToCheck);

	/**
	 * Determine if another Satisfy is equivalent to this one, ignoring
	 * ID's.
	 * @param SatisfyToCheck Satisfy to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * Satisfy are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(ISatisfy SatisfyToCheck);

}
