/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import org.w3c.dom.*;

import edu.uci.isr.xarch.*;

import java.util.*;

/**
 * DOM-Based implementation of the IArchTraceLinks interface.
 *
 * @author Automatically generated by xArch apigen.
 */
public class ArchTraceLinksImpl implements IArchTraceLinks, DOMBased{
	
	public static final String XSD_TYPE_NSURI = TracelinkConstants.NS_URI;
	public static final String XSD_TYPE_NAME = "ArchTraceLinks";
	
	protected IXArch xArch;
	
	/** Tag name for traceLinks in this object. */
	public static final String TRACE_LINK_ELT_NAME = "traceLink";

	
	protected Element elt;
	
	private static SequenceOrder seqOrd = new SequenceOrder(
		new QName[]{
			new QName(TracelinkConstants.NS_URI, TRACE_LINK_ELT_NAME)
		}
	);
	
	public ArchTraceLinksImpl(Element elt){
		if(elt == null){
			throw new IllegalArgumentException("Element cannot be null.");
		}
		this.elt = elt;
	}

	public Node getDOMNode(){
		return elt;
	}
	
	public void setDOMNode(Node node){
		if(node.getNodeType() != Node.ELEMENT_NODE){
			throw new IllegalArgumentException("Base DOM node of this type must be an Element.");
		}
		elt = (Element)node;
	}
	
	protected static SequenceOrder getSequenceOrder(){
		return seqOrd;
	}
	
	public void setXArch(IXArch xArch){
		this.xArch = xArch;
	}
	
	public IXArch getXArch(){
		return this.xArch;
	}

	public IXArchElement cloneElement(int depth){
		synchronized(DOMUtils.getDOMLock(elt)){
			Document doc = elt.getOwnerDocument();
			if(depth == 0){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				ArchTraceLinksImpl cloneImpl = new ArchTraceLinksImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
			else if(depth == 1){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				ArchTraceLinksImpl cloneImpl = new ArchTraceLinksImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				
				NodeList nl = elt.getChildNodes();
				int size = nl.getLength();
				for(int i = 0; i < size; i++){
					Node n = nl.item(i);
					Node cloneNode = (Node)n.cloneNode(false);
					cloneNode = doc.importNode(cloneNode, true);
					cloneElt.appendChild(cloneNode);
				}
				return cloneImpl;
			}
			else /* depth = infinity */{
				Element cloneElt = (Element)elt.cloneNode(true);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				ArchTraceLinksImpl cloneImpl = new ArchTraceLinksImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
		}
	}

	//Override 'equals' to be DOM-based...	
	public boolean equals(Object o){
		if(o == null){
			return false;
		}
		if(!(o instanceof DOMBased)){
			return super.equals(o);
		}
		DOMBased db = (DOMBased)o;
		Node dbNode = db.getDOMNode();
		return dbNode.equals(getDOMNode());
	}

	//Override 'hashCode' to be based on the underlying node
	public int hashCode(){
		return getDOMNode().hashCode();
	}

	/**
	 * For internal use only.
	 */
	private static Object makeDerivedWrapper(Element elt, String baseTypeName){
		synchronized(DOMUtils.getDOMLock(elt)){
			QName typeName = XArchUtils.getXSIType(elt);
			if(typeName == null){
				return null;
			}
			else{
				if(!DOMUtils.hasXSIType(elt, "http://www.ics.uci.edu/pub/arch/xArch/tracelink.xsd", baseTypeName)){
					try{
						String packageTitle = XArchUtils.getPackageTitle(typeName.getNamespaceURI());
						String packageName = XArchUtils.getPackageName(packageTitle);
						String implName = XArchUtils.getImplName(packageName, typeName.getName());
						Class c = Class.forName(implName);
						java.lang.reflect.Constructor con = c.getConstructor(new Class[]{Element.class});
						Object o = con.newInstance(new Object[]{elt});
						return o;
					}
					catch(Exception e){
						//Lots of bad things could happen, but this
						//is OK, because this is best-effort anyway.
					}
				}
				return null;
			}
		}
	}

	public XArchTypeMetadata getTypeMetadata(){
		return IArchTraceLinks.TYPE_METADATA;
	}

	public XArchInstanceMetadata getInstanceMetadata(){
		return new XArchInstanceMetadata(XArchUtils.getPackageTitle(elt.getNamespaceURI()));
	}
	public void addTraceLink(ITraceLink newTraceLink){
		if(!(newTraceLink instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newTraceLink).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TracelinkConstants.NS_URI, TRACE_LINK_ELT_NAME);
		((DOMBased)newTraceLink).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"traceLink", newTraceLink,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addTraceLinks(Collection<ITraceLink> traceLinks){
		for(Iterator en = traceLinks.iterator(); en.hasNext(); ){
			ITraceLink elt = (ITraceLink)en.next();
			addTraceLink(elt);
		}
	}		
		
	public void clearTraceLinks(){
		//DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_ELT_NAME);
		Collection coll = getAllTraceLinks();
		removeTraceLinks(coll);
	}
	
	public void removeTraceLink(ITraceLink traceLinkToRemove){
		if(!(traceLinkToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)traceLinkToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"traceLink", traceLinkToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeTraceLinks(Collection traceLinks){
		for(Iterator en = traceLinks.iterator(); en.hasNext(); ){
			ITraceLink elt = (ITraceLink)en.next();
			removeTraceLink(elt);
		}
	}
	
	public Collection getAllTraceLinks(){
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList v = new ArrayList(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((ITraceLink)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "TraceLink");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((ITraceLink)o);
					}
					catch(Exception e){
						TraceLinkImpl eltImpl = new TraceLinkImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					TraceLinkImpl eltImpl = new TraceLinkImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasTraceLink(ITraceLink traceLinkToCheck){
		Collection c = getAllTraceLinks();
		
		for(Iterator en = c.iterator(); en.hasNext(); ){
			ITraceLink elt = (ITraceLink)en.next();
			if(elt.isEquivalent(traceLinkToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection hasTraceLinks(Collection traceLinksToCheck){
		Vector v = new Vector();
		for(Iterator en = traceLinksToCheck.iterator(); en.hasNext(); ){
			ITraceLink elt = (ITraceLink)en.next();
			v.addElement(new Boolean(hasTraceLink(elt)));
		}
		return v;
	}
		
	public boolean hasAllTraceLinks(Collection traceLinksToCheck){
		for(Iterator en = traceLinksToCheck.iterator(); en.hasNext(); ){
			ITraceLink elt = (ITraceLink)en.next();
			if(!hasTraceLink(elt)){
				return false;
			}
		}
		return true;
	}
	public boolean isEquivalent(IArchTraceLinks c){
		return (getClass().equals(c.getClass())) &&
			hasAllTraceLinks(c.getAllTraceLinks()) &&
			c.hasAllTraceLinks(getAllTraceLinks()) ;
	}

}
