/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * ActionType <code>xsi:type</code> in the
 * tracelink namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IActionType extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"tracelink", "ActionType", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("viewer", "http://www.w3.org/2001/XMLSchema", "string", null, null),
			XArchPropertyMetadata.createElement("description", "instance", "Description", 1, 1),
			XArchPropertyMetadata.createElement("executable", "instance", "XMLLink", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the viewer attribute on this ActionType.
	 * @param viewer viewer
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setViewer(String viewer);

	/**
	 * Remove the viewer attribute from this ActionType.
	 */
	public void clearViewer();

	/**
	 * Get the viewer attribute from this ActionType.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return viewer on this ActionType
	 */
	public String getViewer();

	/**
	 * Determine if the viewer attribute on this ActionType
	 * has the given value.
	 * @param viewer Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasViewer(String viewer);


	/**
	 * Set the description for this ActionType.
	 * @param value new description
	 */
	public void setDescription(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the description from this ActionType.
	 */
	public void clearDescription();

	/**
	 * Get the description from this ActionType.
	 * @return description
	 */
	public edu.uci.isr.xarch.instance.IDescription getDescription();

	/**
	 * Determine if this ActionType has the given description
	 * @param descriptionToCheck description to compare
	 * @return <code>true</code> if the descriptions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDescription(edu.uci.isr.xarch.instance.IDescription descriptionToCheck);

	/**
	 * Set the executable for this ActionType.
	 * @param value new executable
	 */
	public void setExecutable(edu.uci.isr.xarch.instance.IXMLLink value);

	/**
	 * Clear the executable from this ActionType.
	 */
	public void clearExecutable();

	/**
	 * Get the executable from this ActionType.
	 * @return executable
	 */
	public edu.uci.isr.xarch.instance.IXMLLink getExecutable();

	/**
	 * Determine if this ActionType has the given executable
	 * @param executableToCheck executable to compare
	 * @return <code>true</code> if the executables are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasExecutable(edu.uci.isr.xarch.instance.IXMLLink executableToCheck);
	/**
	 * Determine if another ActionType is equivalent to this one, ignoring
	 * ID's.
	 * @param ActionTypeToCheck ActionType to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * ActionType are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IActionType ActionTypeToCheck);

}
