/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * Author <code>xsi:type</code> in the
 * tracelink namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface IAuthor extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"tracelink", "Author", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createAttribute("username", "http://www.w3.org/2001/XMLSchema", "string", null, null),
			XArchPropertyMetadata.createAttribute("groupname", "http://www.w3.org/2001/XMLSchema", "string", null, null)},
		new XArchActionMetadata[]{});

	/**
	 * Set the username attribute on this Author.
	 * @param username username
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setUsername(String username);

	/**
	 * Remove the username attribute from this Author.
	 */
	public void clearUsername();

	/**
	 * Get the username attribute from this Author.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return username on this Author
	 */
	public String getUsername();

	/**
	 * Determine if the username attribute on this Author
	 * has the given value.
	 * @param username Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasUsername(String username);


	/**
	 * Set the groupname attribute on this Author.
	 * @param groupname groupname
	 * @exception FixedValueException if the attribute has a fixed value
	 * and the value passed is not the fixed value.
	*/
	public void setGroupname(String groupname);

	/**
	 * Remove the groupname attribute from this Author.
	 */
	public void clearGroupname();

	/**
	 * Get the groupname attribute from this Author.
	 * if the attribute has a fixed value, this function will
	 * return that fixed value, even if it is not actually present
	 * in the XML document.
	 * @return groupname on this Author
	 */
	public String getGroupname();

	/**
	 * Determine if the groupname attribute on this Author
	 * has the given value.
	 * @param groupname Attribute value to compare
	 * @return <code>true</code> if they match; <code>false</code>
	 * otherwise.
	 */
	public boolean hasGroupname(String groupname);

	/**
	 * Determine if another Author is equivalent to this one, ignoring
	 * ID's.
	 * @param AuthorToCheck Author to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * Author are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(IAuthor AuthorToCheck);

}
