/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * TimeStamp <code>xsi:type</code> in the
 * tracelink namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface ITimeStamp extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"tracelink", "TimeStamp", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("dateTime", "tracelink", "DateTimeStamp", 1, 1),
			XArchPropertyMetadata.createElement("description", "instance", "Description", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the dateTime for this TimeStamp.
	 * @param value new dateTime
	 */
	public void setDateTime(IDateTimeStamp value);

	/**
	 * Clear the dateTime from this TimeStamp.
	 */
	public void clearDateTime();

	/**
	 * Get the dateTime from this TimeStamp.
	 * @return dateTime
	 */
	public IDateTimeStamp getDateTime();

	/**
	 * Determine if this TimeStamp has the given dateTime
	 * @param dateTimeToCheck dateTime to compare
	 * @return <code>true</code> if the dateTimes are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDateTime(IDateTimeStamp dateTimeToCheck);

	/**
	 * Set the description for this TimeStamp.
	 * @param value new description
	 */
	public void setDescription(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the description from this TimeStamp.
	 */
	public void clearDescription();

	/**
	 * Get the description from this TimeStamp.
	 * @return description
	 */
	public edu.uci.isr.xarch.instance.IDescription getDescription();

	/**
	 * Determine if this TimeStamp has the given description
	 * @param descriptionToCheck description to compare
	 * @return <code>true</code> if the descriptions are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasDescription(edu.uci.isr.xarch.instance.IDescription descriptionToCheck);
	/**
	 * Determine if another TimeStamp is equivalent to this one, ignoring
	 * ID's.
	 * @param TimeStampToCheck TimeStamp to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * TimeStamp are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(ITimeStamp TimeStampToCheck);

}
