/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import edu.uci.isr.xarch.XArchActionMetadata;
import edu.uci.isr.xarch.XArchTypeMetadata;
import edu.uci.isr.xarch.XArchPropertyMetadata;

/**
 * Interface for accessing objects of the
 * TraceLinkRelationship <code>xsi:type</code> in the
 * tracelink namespace.
 * 
 * @author Automatically generated by xArch apigen
 */
public interface ITraceLinkRelationship extends edu.uci.isr.xarch.IXArchElement{

	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_ELEMENT,
		"tracelink", "TraceLinkRelationship", edu.uci.isr.xarch.IXArchElement.TYPE_METADATA,
		new XArchPropertyMetadata[]{
			XArchPropertyMetadata.createElement("classification", "instance", "Description", 0, 1)},
		new XArchActionMetadata[]{});

	/**
	 * Set the classification for this TraceLinkRelationship.
	 * @param value new classification
	 */
	public void setClassification(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Clear the classification from this TraceLinkRelationship.
	 */
	public void clearClassification();

	/**
	 * Get the classification from this TraceLinkRelationship.
	 * @return classification
	 */
	public edu.uci.isr.xarch.instance.IDescription getClassification();

	/**
	 * Determine if this TraceLinkRelationship has the given classification
	 * @param classificationToCheck classification to compare
	 * @return <code>true</code> if the classifications are equivalent,
	 * <code>false</code> otherwise
	 */
	public boolean hasClassification(edu.uci.isr.xarch.instance.IDescription classificationToCheck);
	/**
	 * Determine if another TraceLinkRelationship is equivalent to this one, ignoring
	 * ID's.
	 * @param TraceLinkRelationshipToCheck TraceLinkRelationship to compare to this one.
	 * @return <code>true</code> if all the child elements of this
	 * TraceLinkRelationship are equivalent, <code>false</code> otherwise.
	 */
	public boolean isEquivalent(ITraceLinkRelationship TraceLinkRelationshipToCheck);

}
