/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import java.util.*;

import edu.uci.isr.xarch.*;

import edu.uci.isr.xarch.IXArch;
import edu.uci.isr.xarch.IXArchContext;

/**
 * The context interface for the tracelink package.
 * This interface is used to create objects that are used
 * in the tracelink namespace.
 *
 * @author Automatically Generated by xArch apigen
 */
public interface ITracelinkContext extends IXArchContext{

	/**
	 * Create an IStatusSimple object in this namespace.
	 * @return New IStatusSimple object.
	 */
	public IStatusSimple createStatusSimple();

	/**
	 * Brings an IStatusSimple object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IStatusSimple recontextualizeStatusSimple(IStatusSimple value);

	/**
	 * Create an IDateTimeStamp object in this namespace.
	 * @return New IDateTimeStamp object.
	 */
	public IDateTimeStamp createDateTimeStamp();

	/**
	 * Brings an IDateTimeStamp object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IDateTimeStamp recontextualizeDateTimeStamp(IDateTimeStamp value);

	/**
	 * Create an ICaptureModeSimple object in this namespace.
	 * @return New ICaptureModeSimple object.
	 */
	public ICaptureModeSimple createCaptureModeSimple();

	/**
	 * Brings an ICaptureModeSimple object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ICaptureModeSimple recontextualizeCaptureModeSimple(ICaptureModeSimple value);

	/**
	 * Create an IArchTraceLinks object in this namespace.
	 * @return New IArchTraceLinks object.
	 */
	public IArchTraceLinks createArchTraceLinks();

	/**
	 * Brings an IArchTraceLinks object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IArchTraceLinks recontextualizeArchTraceLinks(IArchTraceLinks value);

	/**
	 * Create an ITraceLink object in this namespace.
	 * @return New ITraceLink object.
	 */
	public ITraceLink createTraceLink();

	/**
	 * Brings an ITraceLink object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ITraceLink recontextualizeTraceLink(ITraceLink value);

	/**
	 * Create an edu.uci.isr.xarch.instance.IDescription object in this namespace.
	 * @return New edu.uci.isr.xarch.instance.IDescription object.
	 */
	public edu.uci.isr.xarch.instance.IDescription createDescription();

	/**
	 * Brings an edu.uci.isr.xarch.instance.IDescription object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public edu.uci.isr.xarch.instance.IDescription recontextualizeDescription(edu.uci.isr.xarch.instance.IDescription value);

	/**
	 * Create an ITraceEndpoint object in this namespace.
	 * @return New ITraceEndpoint object.
	 */
	public ITraceEndpoint createTraceEndpoint();

	/**
	 * Brings an ITraceEndpoint object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ITraceEndpoint recontextualizeTraceEndpoint(ITraceEndpoint value);

	/**
	 * Create an edu.uci.isr.xarch.instance.IXMLLink object in this namespace.
	 * @return New edu.uci.isr.xarch.instance.IXMLLink object.
	 */
	public edu.uci.isr.xarch.instance.IXMLLink createXMLLink();

	/**
	 * Brings an edu.uci.isr.xarch.instance.IXMLLink object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public edu.uci.isr.xarch.instance.IXMLLink recontextualizeXMLLink(edu.uci.isr.xarch.instance.IXMLLink value);

	/**
	 * Create an ITraceLinkRelationship object in this namespace.
	 * @return New ITraceLinkRelationship object.
	 */
	public ITraceLinkRelationship createTraceLinkRelationship();

	/**
	 * Brings an ITraceLinkRelationship object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ITraceLinkRelationship recontextualizeTraceLinkRelationship(ITraceLinkRelationship value);

	/**
	 * Create an IStatus object in this namespace.
	 * @return New IStatus object.
	 */
	public IStatus createStatus();

	/**
	 * Brings an IStatus object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IStatus recontextualizeStatus(IStatus value);

	/**
	 * Create an IAuthor object in this namespace.
	 * @return New IAuthor object.
	 */
	public IAuthor createAuthor();

	/**
	 * Brings an IAuthor object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IAuthor recontextualizeAuthor(IAuthor value);

	/**
	 * Create an ITimeStamp object in this namespace.
	 * @return New ITimeStamp object.
	 */
	public ITimeStamp createTimeStamp();

	/**
	 * Brings an ITimeStamp object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ITimeStamp recontextualizeTimeStamp(ITimeStamp value);

	/**
	 * Create an ICaptureMode object in this namespace.
	 * @return New ICaptureMode object.
	 */
	public ICaptureMode createCaptureMode();

	/**
	 * Brings an ICaptureMode object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public ICaptureMode recontextualizeCaptureMode(ICaptureMode value);

	/**
	 * Create an IActionType object in this namespace.
	 * @return New IActionType object.
	 */
	public IActionType createActionType();

	/**
	 * Brings an IActionType object created in another
	 * context into this context.
	 * @param value Object to recontextualize.
	 * @return <code>value</code> object in this namespace.
	 */
	public IActionType recontextualizeActionType(IActionType value);

	/**
	 * Create a top-level element of type <code>IArchTraceLinks</code>.
	 * This function should be used in lieu of <code>createArchTraceLinks</code>
	 * if the element is to be added as a sub-object of <code>IXArch</code>.
	 * @return new IArchTraceLinks suitable for adding
	 * as a child of xArch.
	 */
	public IArchTraceLinks createArchTraceLinksElement();

	/**
	 * Gets the IArchTraceLinks child from the given <code>IXArch</code>
	 * element.  If there are multiple matching children, this returns the first one.
	 * @param xArch <code>IXArch</code> object from which to get the child.
	 * @return <code>IArchTraceLinks</code> that is the child
	 * of <code>xArch</code> or <code>null</code> if no such object exists.
	 */
	public IArchTraceLinks getArchTraceLinks(IXArch xArch);

	/**
	 * Gets all the IArchTraceLinks children from the given 
	 * <code>IXArch</code> element.
	 * @param xArch <code>IXArch</code> object from which to get the children.
	 * @return Collection of <code>IArchTraceLinks</code> that are 	
	 * the children of <code>xArch</code> or an empty collection if no such object exists.
	 */
	public Collection<IArchTraceLinks> getAllArchTraceLinkss(IXArch xArch);


	public final static XArchTypeMetadata TYPE_METADATA = new XArchTypeMetadata(
		XArchTypeMetadata.XARCH_CONTEXT,
		"tracelink", null, null,
		new XArchPropertyMetadata[]{},
		new XArchActionMetadata[]{
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IStatusSimple.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IStatusSimple.TYPE_METADATA, IStatusSimple.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IDateTimeStamp.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IDateTimeStamp.TYPE_METADATA, IDateTimeStamp.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ICaptureModeSimple.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ICaptureModeSimple.TYPE_METADATA, ICaptureModeSimple.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IArchTraceLinks.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IArchTraceLinks.TYPE_METADATA, IArchTraceLinks.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ITraceLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ITraceLink.TYPE_METADATA, ITraceLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, edu.uci.isr.xarch.instance.IDescription.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, edu.uci.isr.xarch.instance.IDescription.TYPE_METADATA, edu.uci.isr.xarch.instance.IDescription.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ITraceEndpoint.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ITraceEndpoint.TYPE_METADATA, ITraceEndpoint.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA, edu.uci.isr.xarch.instance.IXMLLink.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ITraceLinkRelationship.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ITraceLinkRelationship.TYPE_METADATA, ITraceLinkRelationship.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IStatus.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IStatus.TYPE_METADATA, IStatus.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IAuthor.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IAuthor.TYPE_METADATA, IAuthor.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ITimeStamp.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ITimeStamp.TYPE_METADATA, ITimeStamp.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, ICaptureMode.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, ICaptureMode.TYPE_METADATA, ICaptureMode.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE, null, IActionType.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.RECONTEXTUALIZE, IActionType.TYPE_METADATA, IActionType.TYPE_METADATA),
			new XArchActionMetadata(XArchActionMetadata.CREATE_ELEMENT, null, IArchTraceLinks.TYPE_METADATA)});

}

