/*
 * Copyright (c) 2000-2005 Regents of the University of California.
 * All rights reserved.
 *
 * This software was developed at the University of California, Irvine.
 *
 * Redistribution and use in source and binary forms are permitted
 * provided that the above copyright notice and this paragraph are
 * duplicated in all such forms and that any documentation,
 * advertising materials, and other materials related to such
 * distribution and use acknowledge that the software was developed
 * by the University of California, Irvine.  The name of the
 * University may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */
package edu.uci.isr.xarch.tracelink;

import org.w3c.dom.*;

import edu.uci.isr.xarch.*;

import java.util.*;

/**
 * DOM-Based implementation of the ITraceLink interface.
 *
 * @author Automatically generated by xArch apigen.
 */
public class TraceLinkImpl implements ITraceLink, DOMBased{
	
	public static final String XSD_TYPE_NSURI = TracelinkConstants.NS_URI;
	public static final String XSD_TYPE_NAME = "TraceLink";
	
	protected IXArch xArch;
	
	/** Tag name for traceLinkIDs in this object. */
	public static final String TRACE_LINK_I_D_ATTR_NAME = "traceLinkID";
	/** Tag name for descriptions in this object. */
	public static final String DESCRIPTION_ELT_NAME = "description";
	/** Tag name for traceLinkRelationships in this object. */
	public static final String TRACE_LINK_RELATIONSHIP_ELT_NAME = "traceLinkRelationship";
	/** Tag name for traceEndpoints in this object. */
	public static final String TRACE_ENDPOINT_ELT_NAME = "traceEndpoint";

	
	protected Element elt;
	
	private static SequenceOrder seqOrd = new SequenceOrder(
		new QName[]{
			new QName(TracelinkConstants.NS_URI, DESCRIPTION_ELT_NAME),
			new QName(TracelinkConstants.NS_URI, TRACE_LINK_RELATIONSHIP_ELT_NAME),
			new QName(TracelinkConstants.NS_URI, TRACE_ENDPOINT_ELT_NAME)
		}
	);
	
	public TraceLinkImpl(Element elt){
		if(elt == null){
			throw new IllegalArgumentException("Element cannot be null.");
		}
		this.elt = elt;
	}

	public Node getDOMNode(){
		return elt;
	}
	
	public void setDOMNode(Node node){
		if(node.getNodeType() != Node.ELEMENT_NODE){
			throw new IllegalArgumentException("Base DOM node of this type must be an Element.");
		}
		elt = (Element)node;
	}
	
	protected static SequenceOrder getSequenceOrder(){
		return seqOrd;
	}
	
	public void setXArch(IXArch xArch){
		this.xArch = xArch;
	}
	
	public IXArch getXArch(){
		return this.xArch;
	}

	public IXArchElement cloneElement(int depth){
		synchronized(DOMUtils.getDOMLock(elt)){
			Document doc = elt.getOwnerDocument();
			if(depth == 0){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				TraceLinkImpl cloneImpl = new TraceLinkImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
			else if(depth == 1){
				Element cloneElt = (Element)elt.cloneNode(false);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				TraceLinkImpl cloneImpl = new TraceLinkImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				
				NodeList nl = elt.getChildNodes();
				int size = nl.getLength();
				for(int i = 0; i < size; i++){
					Node n = nl.item(i);
					Node cloneNode = (Node)n.cloneNode(false);
					cloneNode = doc.importNode(cloneNode, true);
					cloneElt.appendChild(cloneNode);
				}
				return cloneImpl;
			}
			else /* depth = infinity */{
				Element cloneElt = (Element)elt.cloneNode(true);
				cloneElt = (Element)doc.importNode(cloneElt, true);
				TraceLinkImpl cloneImpl = new TraceLinkImpl(cloneElt);
				cloneImpl.setXArch(getXArch());
				return cloneImpl;
			}
		}
	}

	//Override 'equals' to be DOM-based...	
	public boolean equals(Object o){
		if(o == null){
			return false;
		}
		if(!(o instanceof DOMBased)){
			return super.equals(o);
		}
		DOMBased db = (DOMBased)o;
		Node dbNode = db.getDOMNode();
		return dbNode.equals(getDOMNode());
	}

	//Override 'hashCode' to be based on the underlying node
	public int hashCode(){
		return getDOMNode().hashCode();
	}

	/**
	 * For internal use only.
	 */
	private static Object makeDerivedWrapper(Element elt, String baseTypeName){
		synchronized(DOMUtils.getDOMLock(elt)){
			QName typeName = XArchUtils.getXSIType(elt);
			if(typeName == null){
				return null;
			}
			else{
				if(!DOMUtils.hasXSIType(elt, "http://www.ics.uci.edu/pub/arch/xArch/tracelink.xsd", baseTypeName)){
					try{
						String packageTitle = XArchUtils.getPackageTitle(typeName.getNamespaceURI());
						String packageName = XArchUtils.getPackageName(packageTitle);
						String implName = XArchUtils.getImplName(packageName, typeName.getName());
						Class c = Class.forName(implName);
						java.lang.reflect.Constructor con = c.getConstructor(new Class[]{Element.class});
						Object o = con.newInstance(new Object[]{elt});
						return o;
					}
					catch(Exception e){
						//Lots of bad things could happen, but this
						//is OK, because this is best-effort anyway.
					}
				}
				return null;
			}
		}
	}

	public XArchTypeMetadata getTypeMetadata(){
		return ITraceLink.TYPE_METADATA;
	}

	public XArchInstanceMetadata getInstanceMetadata(){
		return new XArchInstanceMetadata(XArchUtils.getPackageTitle(elt.getNamespaceURI()));
	}
	/**
	 * Set the traceLinkID attribute on this object.
	 * @param traceLinkID attribute value.
	 */
	public void setTraceLinkID(String traceLinkID){
		{
			String oldValue = getTraceLinkID();
			if(oldValue == null ? traceLinkID == null : oldValue.equals(traceLinkID))
				return;
			DOMUtils.removeAttribute(elt, TracelinkConstants.NS_URI, TRACE_LINK_I_D_ATTR_NAME);
			IXArch _x = getXArch();
			if(_x != null){
				_x.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ATTRIBUTE_CHANGED,
					"traceLinkID", oldValue,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		DOMUtils.setAttribute(elt, TracelinkConstants.NS_URI, TRACE_LINK_I_D_ATTR_NAME, traceLinkID);
		IXArch _x = getXArch();
		if(_x != null){
			_x.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ATTRIBUTE_CHANGED,
				"traceLinkID", traceLinkID,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	/**
	 * Removes the traceLinkID attribute from this object.
	 */
	public void clearTraceLinkID(){
		String oldValue = getTraceLinkID();
		if(oldValue == null)
			return;
		DOMUtils.removeAttribute(elt, TracelinkConstants.NS_URI, TRACE_LINK_I_D_ATTR_NAME);
		IXArch _x = getXArch();
		if(_x != null){
			_x.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ATTRIBUTE_CHANGED,
				"traceLinkID", oldValue,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	/**
	 * Gets the value of the traceLinkID attribute on this object.
	 * @return traceLinkID attribute's value or <code>null</code> if that
	 * attribute is not set.
	 */
	public String getTraceLinkID(){
		return DOMUtils.getAttributeValue(elt, TracelinkConstants.NS_URI, TRACE_LINK_I_D_ATTR_NAME);
	}
	
	/**
	 * Determines if this object's traceLinkID attribute has the
	 * given value.
	 * @param traceLinkID value to test.
	 * @return <code>true</code> if the values match, <code>false</code> otherwise.
	 * Matching is done by string-matching.
	 */
	public boolean hasTraceLinkID(String traceLinkID){
		return DOMUtils.objNullEq(getTraceLinkID(), traceLinkID);
	}


	public void setDescription(edu.uci.isr.xarch.instance.IDescription value){
		if(!(value instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		{
			edu.uci.isr.xarch.instance.IDescription oldElt = getDescription();
			DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, DESCRIPTION_ELT_NAME);
			
			IXArch context = getXArch();
			if(context != null){
				context.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ELEMENT_CHANGED,
					"description", oldElt,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		Element newChildElt = (Element)(((DOMBased)value).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TracelinkConstants.NS_URI, DESCRIPTION_ELT_NAME);
		((DOMBased)value).setDOMNode(newChildElt);
		
		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"description", value,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public void clearDescription(){
		edu.uci.isr.xarch.instance.IDescription oldElt = getDescription();
		DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, DESCRIPTION_ELT_NAME);
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"description", oldElt,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public edu.uci.isr.xarch.instance.IDescription getDescription(){
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, DESCRIPTION_ELT_NAME);
		if(nl.getLength() == 0){
			return null;
		}
		else{
			Element el = (Element)nl.item(0);
			IXArch de = getXArch();
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					return (edu.uci.isr.xarch.instance.IDescription)cachedXArchElt;
				}
			}
			
			Object o = makeDerivedWrapper(el, "Description");
			if(o != null){
				try{
					((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
					}
					return (edu.uci.isr.xarch.instance.IDescription)o;
				}
				catch(Exception e){}
			}
			edu.uci.isr.xarch.instance.DescriptionImpl eltImpl = new edu.uci.isr.xarch.instance.DescriptionImpl(el);
			eltImpl.setXArch(getXArch());
			if(de != null){
				de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
			}
			return eltImpl;
		}
	}
	
	public boolean hasDescription(edu.uci.isr.xarch.instance.IDescription value){
		edu.uci.isr.xarch.instance.IDescription thisValue = getDescription();
		edu.uci.isr.xarch.instance.IDescription thatValue = value;
		
		if((thisValue == null) && (thatValue == null)){
			return true;
		}
		else if((thisValue == null) && (thatValue != null)){
			return false;
		}
		else if((thisValue != null) && (thatValue == null)){
			return false;
		}
		return thisValue.isEquivalent(thatValue);
	}


	public void setTraceLinkRelationship(ITraceLinkRelationship value){
		if(!(value instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		{
			ITraceLinkRelationship oldElt = getTraceLinkRelationship();
			DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_RELATIONSHIP_ELT_NAME);
			
			IXArch context = getXArch();
			if(context != null){
				context.fireXArchEvent(
					new XArchEvent(this, 
					XArchEvent.CLEAR_EVENT,
					XArchEvent.ELEMENT_CHANGED,
					"traceLinkRelationship", oldElt,
					XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this), true)
				);
			}
		}
		Element newChildElt = (Element)(((DOMBased)value).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TracelinkConstants.NS_URI, TRACE_LINK_RELATIONSHIP_ELT_NAME);
		((DOMBased)value).setDOMNode(newChildElt);
		
		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.SET_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"traceLinkRelationship", value,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public void clearTraceLinkRelationship(){
		ITraceLinkRelationship oldElt = getTraceLinkRelationship();
		DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_RELATIONSHIP_ELT_NAME);
		
		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.CLEAR_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"traceLinkRelationship", oldElt,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
	
	public ITraceLinkRelationship getTraceLinkRelationship(){
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, TRACE_LINK_RELATIONSHIP_ELT_NAME);
		if(nl.getLength() == 0){
			return null;
		}
		else{
			Element el = (Element)nl.item(0);
			IXArch de = getXArch();
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					return (ITraceLinkRelationship)cachedXArchElt;
				}
			}
			
			Object o = makeDerivedWrapper(el, "TraceLinkRelationship");
			if(o != null){
				try{
					((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
					}
					return (ITraceLinkRelationship)o;
				}
				catch(Exception e){}
			}
			TraceLinkRelationshipImpl eltImpl = new TraceLinkRelationshipImpl(el);
			eltImpl.setXArch(getXArch());
			if(de != null){
				de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
			}
			return eltImpl;
		}
	}
	
	public boolean hasTraceLinkRelationship(ITraceLinkRelationship value){
		ITraceLinkRelationship thisValue = getTraceLinkRelationship();
		ITraceLinkRelationship thatValue = value;
		
		if((thisValue == null) && (thatValue == null)){
			return true;
		}
		else if((thisValue == null) && (thatValue != null)){
			return false;
		}
		else if((thisValue != null) && (thatValue == null)){
			return false;
		}
		return thisValue.isEquivalent(thatValue);
	}

	public void addTraceEndpoint(ITraceEndpoint newTraceEndpoint){
		if(!(newTraceEndpoint instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		Element newChildElt = (Element)(((DOMBased)newTraceEndpoint).getDOMNode());
		newChildElt = DOMUtils.cloneAndRename(newChildElt, TracelinkConstants.NS_URI, TRACE_ENDPOINT_ELT_NAME);
		((DOMBased)newTraceEndpoint).setDOMNode(newChildElt);

		synchronized(DOMUtils.getDOMLock(elt)){
			elt.appendChild(newChildElt);
			DOMUtils.order(elt, getSequenceOrder());
		}

		IXArch context = getXArch();
		if(context != null){
			context.fireXArchEvent(
				new XArchEvent(this, 
				XArchEvent.ADD_EVENT,
				XArchEvent.ELEMENT_CHANGED,
				"traceEndpoint", newTraceEndpoint,
				XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
			);
		}
	}
		
	public void addTraceEndpoints(Collection<ITraceEndpoint> traceEndpoints){
		for(ITraceEndpoint elt : traceEndpoints){
			addTraceEndpoint(elt);
		}
	}		
		
	public void clearTraceEndpoints(){
		//DOMUtils.removeChildren(elt, TracelinkConstants.NS_URI, TRACE_ENDPOINT_ELT_NAME);
		Collection<ITraceEndpoint> coll = getAllTraceEndpoints();
		removeTraceEndpoints(coll);
	}
	
	public void removeTraceEndpoint(ITraceEndpoint traceEndpointToRemove){
		if(!(traceEndpointToRemove instanceof DOMBased)){
			throw new IllegalArgumentException("Cannot handle non-DOM-based xArch entities.");
		}
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, TRACE_ENDPOINT_ELT_NAME);
		for(int i = 0; i < nl.getLength(); i++){
			Node n = nl.item(i);
			if(n == ((DOMBased)traceEndpointToRemove).getDOMNode()){
				synchronized(DOMUtils.getDOMLock(elt)){
					elt.removeChild(n);
				}

				IXArch context = getXArch();
				if(context != null){
					context.fireXArchEvent(
						new XArchEvent(this, 
						XArchEvent.REMOVE_EVENT,
						XArchEvent.ELEMENT_CHANGED,
						"traceEndpoint", traceEndpointToRemove,
						XArchUtils.getDefaultXArchImplementation().isContainedIn(xArch, this))
					);
				}

				return;
			}
		}
	}
	
	public void removeTraceEndpoints(Collection<ITraceEndpoint> traceEndpoints){
		for(ITraceEndpoint elt : traceEndpoints){
			removeTraceEndpoint(elt);
		}
	}
	
	public Collection<ITraceEndpoint> getAllTraceEndpoints(){
		NodeList nl = DOMUtils.getChildren(elt, TracelinkConstants.NS_URI, TRACE_ENDPOINT_ELT_NAME);
		int nlLength = nl.getLength();
		ArrayList<ITraceEndpoint> v = new ArrayList<ITraceEndpoint>(nlLength);
		IXArch de = getXArch();
		for(int i = 0; i < nlLength; i++){
			Element el = (Element)nl.item(i);
			boolean found = false;
			if(de != null){
				IXArchElement cachedXArchElt = de.getWrapper(el);
				if(cachedXArchElt != null){
					v.add((ITraceEndpoint)cachedXArchElt);
					found = true;
				}
			}
			if(!found){
				Object o = makeDerivedWrapper(el, "TraceEndpoint");	
				if(o != null){
					try{
						((edu.uci.isr.xarch.IXArchElement)o).setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)o));
						}
						v.add((ITraceEndpoint)o);
					}
					catch(Exception e){
						TraceEndpointImpl eltImpl = new TraceEndpointImpl((Element)nl.item(i));
						eltImpl.setXArch(getXArch());
						if(de != null){
							de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
						}
						v.add(eltImpl);
					}
				}
				else{
					TraceEndpointImpl eltImpl = new TraceEndpointImpl((Element)nl.item(i));
					eltImpl.setXArch(getXArch());
					if(de != null){
						de.cacheWrapper(el, ((edu.uci.isr.xarch.IXArchElement)eltImpl));
					}
					v.add(eltImpl);
				}
			}
		}
		return v;
	}

	public boolean hasTraceEndpoint(ITraceEndpoint traceEndpointToCheck){
		Collection<ITraceEndpoint> c = getAllTraceEndpoints();
		
		for(ITraceEndpoint elt : c){
			if(elt.isEquivalent(traceEndpointToCheck)){
				return true;
			}
		}
		return false;
	}
	
	public Collection<Boolean> hasTraceEndpoints(Collection<ITraceEndpoint> traceEndpointsToCheck){
		Vector<Boolean> v = new Vector<Boolean>();
		for(ITraceEndpoint elt : traceEndpointsToCheck){
			v.addElement(new Boolean(hasTraceEndpoint(elt)));
		}
		return v;
	}
		
	public boolean hasAllTraceEndpoints(Collection<ITraceEndpoint> traceEndpointsToCheck){
		for(ITraceEndpoint elt : traceEndpointsToCheck){
			if(!hasTraceEndpoint(elt)){
				return false;
			}
		}
		return true;
	}
	public boolean isEquivalent(ITraceLink c){
		return (getClass().equals(c.getClass())) &&
		hasTraceLinkID(c.getTraceLinkID()) &&
			hasDescription(c.getDescription()) &&
			hasTraceLinkRelationship(c.getTraceLinkRelationship()) &&
			hasAllTraceEndpoints(c.getAllTraceEndpoints()) &&
			c.hasAllTraceEndpoints(getAllTraceEndpoints()) ;
	}

}
